config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "articles#index"
  resources :articles do
    resources :comments, only: [:create]
  end
  post '/new_user_reaction', to: 'reactions#new_user_reaction', as: 'new_user_reaction'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy

  Kinds = %w[like dislike not_interested neutral].freeze
  KindsSpanish = {
    "like" => "Me gusta", 
    "dislike" => "No me gusta",
    "not_interested" => "No me interesa", 
    "neutral" => "Neutral"
  }.freeze
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user, optional: true
  has_many :reactions, dependent: :destroy
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :user
  belongs_to :article, optional: true
  belongs_to :comment, optional: true

  validates :kind, presence: true
  validate :either_article_or_comment

  private

  def either_article_or_comment
    if article.nil? && comment.nil?
      errors.add(:base, "Reaction should belong to either an article or a comment, not both.")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_many :articles
  has_many :comments
  has_many :reactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  
  def index
    @articles = Article.order(:created_at).page(params[:page]).per(10)
  end
  
  def show
    @comment = Comment.new
    @comments = @article.comments
  end
  
  def new
    @article = current_user.articles.build
  end
  
  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to @article, notice: 'El articulo fue creado exitosamente.'
    else
      render :new
    end
  end
  
  private
  
  def set_article
    @article = Article.find(params[:id])
  end
  
  def article_params
    params.require(:article).permit(:title, :description)
  end
end

  

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      @article = Article.find(params[:comment][:article_id])
      @comment = @article.comments.build(comment_params)
      @comment.user = current_user
  
      if @comment.save
        redirect_to @article, notice: 'Comment was successfully created.'
      else
        redirect_to @article, alert: 'Failed to create comment.'
      end
    end
  
    private
  
    def comment_params
      params.require(:comment).permit(:content, :anonymous)
    end
  end
  

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
    def new_user_reaction
      @user = current_user
      @article = Article.find(params[:article_id]) if params[:article_id]
      @comment = Comment.find(params[:comment_id]) if params[:comment_id]
      @kind = params[:kind]
      @reaction = Reaction.new(user: @user, article: @article, kind: @kind)
  
      if @reaction.save
        redirect_to article_path(@article), notice: 'Reaction was successfully created.'
      else
        redirect_to article_path(@article), alert: 'Something went wrong.'
      end
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<div class="ms-4">
<h1>Artículos</h1>
<%= link_to 'Nuevo artículo', new_article_path, class: 'btn btn-primary mb-4' %>
</div>
<div class="row ms-auto me-auto">
  <% @articles.each do |article| %>
    <div class="col-md-3 mb-4">
      <div class="card">
        
        <div class="card-body">
          <h5 class="card-title"><%= article.title %></h5>
          <p class="card-text"><%= truncate(article.description, length: 80) %></p>
          <%= link_to 'Leer más', article_path(article), class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="pagination ms-3">
  <%= paginate @articles %>
</div>

app/views/articles/new.html.erb
<div class="ms-5">
<h1>Nuevo Artículo</h1>

<%= form_with(model: @article, local: true) do |form| %>
  <div class='mb-4'>
    <div>
    <%= form.label :title, "Título" %>
    </div>
    <div>
    <%= form.text_field :title %>
    </div>
  </div>

  <div class='mb-4'>
    <div>
    <%= form.label :description, "Descripción" %>
    </div>
    <div>
    <%= form.text_area :description %>
    </div>
  </div>

  <div>
    <%= form.submit "Crear Artículo" %>
  </div>
<% end %>
</div>

app/views/articles/show.html.erb
<div class='ms-4 me-4'>
<h1><%= @article.title %></h1>
<p><%= @article.description %></p>
</div>
<div class='ms-4 me-4'>
<h2>Comentarios</h2>
<%= render 'comments/article_comments', comments: @comments %>
</div>
<div class='ms-5'>
<%= render 'comments/form', article: @article, comment: @comment %>
</div>

app/views/comments/_article_comments.html.erb
<ul>
  <% comments.each do |comment| %>
    <li>
      <%= comment.content %>
      <p><%= comment.user.name unless comment.anonymous %></p>
    </li>
  <% end %>
</ul>

app/views/comments/_form.html.erb
<%= form_with(model: [article, comment], local: true) do |form| %>
  <div>
    <%= form.text_area :content, placeholder: "Añade tu comentario" %>
  </div>

  <div>
    <%= form.label :anonymous, "Comentario anónimo?" %>
    <%= form.check_box :anonymous %>
  </div>

  <div>
    <%= form.submit "Comentar" %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Crazy4Cats', root_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Nuevo artículo', new_article_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= button_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Iniciar sesión', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Registrarse', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crazy4Cats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>